### ISSUE TITLE
怎么使用？

### ISSUE THREAD

**Issue by briteming** [ifTNT/SocksOverHttp#1]
hi.

在vps上。
cd $GOPATH
go get -u -v github.com/ifTNT/SocksOverHttp/
which SocksOverHttp
显示：
/root/go1.13/go/gopath/bin/SocksOverHttp

说明SocksOverHttp安装成功。
运行SocksOverHttp -h 没有显示。
运行SocksOverHttp --help也没有显示。
那么怎么使用？怎么使用它翻墙呢？

**Comment by ifTNT** [comment]
hello,

這個專案目前版本是無法使用的狀態
同性質的專案可以參考
https://github.com/mmis1000/web-socket-socket5-proxy
這個專案將可以將 Socks 的流量透過 WebSocket Tunnel 送至牆外的伺服器
